---
apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "jupyter-notebook"
spec:
  app: "jupyter-notebook"
  appCatalog: "local"
#  connections:
#    secrets:
#      - "hpecp-ext-auth-secret"
#      - "hpecp-source-control-secret-d4c2c7467201788666a6347ce339fc41"
#    clusters:
#      - "training-cluster"
  roles:
    -
      id: "controller"
      members: 1
      resources:
        requests:
          memory: "2Gi"
          cpu: "2"
        limits:
          memory: "2Gi"
          cpu: "2"
#      podLabels:
#        hpecp.hpe.com/dtap: "inject"